### ISSUE TITLE
could not run test.

### ISSUE THREAD

**Issue by huiman** [Tripouille/libftTester#42]
using ubuntu 20.04 in wsl.
after call make m:

Already up to date.
If all your tests are OK and the moulinette KO you, please run the tester with valgrind (see README)
make -C /home/hui/cardet/libft
make[1]: Entering directory '/home/hui/cardet/libft'
make[1]: 'libft.a' is up to date.
make[1]: Leaving directory '/home/hui/cardet/libft'
[Mandatory]
/usr/bin/ld: /tmp/ft_memset_test-332b90.o: in function `main':
/home/hui/cardet/libft/libftTester/tests/ft_memset_test.cpp:22: undefined reference to `ft_memset'
/usr/bin/ld: /home/hui/cardet/libft/libftTester/tests/ft_memset_test.cpp:24: undefined reference to `ft_memset'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:24: memset] Error 1

**Comment by Chinimala** [comment]
Hello @huiman , you should avoid creating issues in repositories because you have difficulties using them. Rather ask colleagues! Also, when creating an issue, give more information: snippets of code, what you tried...

For your problem, as stated in the error, `ft_memset` isn't found by the tester. Maybe your function isn't named right, in the .c or the .h? Does it work when you test it yourself (with a little main.c for example)?

**Comment by huiman** [comment]
Thanks, @Chinimala! I resolved the issue by copying my project's *.c, *.h, and Makefile to a new directory for testing. During this process, I discovered that the root cause of the problem was the presence of the "en.subject.pdf" file in the same directory as my working files.

**Comment by huiman** [comment]
😄
